// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HelloIn
	HelloOut
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// import _ "google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloIn struct {
	In string `protobuf:"bytes,1,opt,name=in" json:"in,omitempty"`
}

func (m *HelloIn) Reset()                    { *m = HelloIn{} }
func (m *HelloIn) String() string            { return proto.CompactTextString(m) }
func (*HelloIn) ProtoMessage()               {}
func (*HelloIn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HelloOut struct {
	Out string `protobuf:"bytes,1,opt,name=out" json:"out,omitempty"`
}

func (m *HelloOut) Reset()                    { *m = HelloOut{} }
func (m *HelloOut) String() string            { return proto.CompactTextString(m) }
func (*HelloOut) ProtoMessage()               {}
func (*HelloOut) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*HelloIn)(nil), "api.HelloIn")
	proto.RegisterType((*HelloOut)(nil), "api.HelloOut")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for HelloWorld service

type HelloWorldClient interface {
	SayHello(ctx context.Context, in *HelloIn, opts ...grpc.CallOption) (*HelloOut, error)
}

type helloWorldClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldClient(cc *grpc.ClientConn) HelloWorldClient {
	return &helloWorldClient{cc}
}

func (c *helloWorldClient) SayHello(ctx context.Context, in *HelloIn, opts ...grpc.CallOption) (*HelloOut, error) {
	out := new(HelloOut)
	err := grpc.Invoke(ctx, "/api.HelloWorld/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloWorld service

type HelloWorldServer interface {
	SayHello(context.Context, *HelloIn) (*HelloOut, error)
}

func RegisterHelloWorldServer(s *grpc.Server, srv HelloWorldServer) {
	s.RegisterService(&_HelloWorld_serviceDesc, srv)
}

func _HelloWorld_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HelloWorld/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServer).SayHello(ctx, req.(*HelloIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorld_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HelloWorld",
	HandlerType: (*HelloWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloWorld_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc,
	0xcf, 0x2b, 0x86, 0x28, 0x51, 0x92, 0xe4, 0x62, 0xf7, 0x48, 0xcd, 0xc9, 0xc9, 0xf7, 0xcc, 0x13,
	0xe2, 0xe3, 0x62, 0xca, 0xcc, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0xcc, 0x53,
	0x92, 0xe1, 0xe2, 0x00, 0x4b, 0xf9, 0x97, 0x96, 0x08, 0x09, 0x70, 0x31, 0xe7, 0x97, 0x96, 0x40,
	0x25, 0x41, 0x4c, 0x23, 0x5f, 0x2e, 0x2e, 0xb0, 0x6c, 0x78, 0x7e, 0x51, 0x4e, 0x8a, 0x90, 0x3d,
	0x17, 0x47, 0x70, 0x62, 0x25, 0x58, 0x40, 0x88, 0x47, 0x0f, 0xe4, 0x02, 0xa8, 0xa9, 0x52, 0xbc,
	0x08, 0x9e, 0x7f, 0x69, 0x89, 0x92, 0x58, 0xd3, 0xe5, 0x27, 0x93, 0x99, 0x04, 0x84, 0xf8, 0xf4,
	0xcb, 0x0c, 0xf5, 0x33, 0x40, 0xa2, 0xfa, 0xd5, 0x99, 0x79, 0xb5, 0x49, 0x6c, 0x60, 0xe7, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x54, 0x8a, 0xea, 0xbe, 0x00, 0x00, 0x00,
}
